#news_agent:
#  idea: "Short movie postcast, colloquial expression within 300 words, notice to identify which actor or host is talking, don't mention movie tickets available issue."
#  output: "dataset/user_output_video/news_output_video_subtitle.mp4"

## Video Assets Directory
#  video_source_dir: "dataset/user_video/"
