# talk_show:
#   reqs: '无'
#   audio_path: 'dataset/talk_show/郭德纲于谦双口.wav'
#   target: 'dataset/talk_show/guodegang'
#   output: "dataset/user_output_video/output_video.mp4"
#   video_source_dir: "dataset/user_video/"